--ALTER Table Schema
ALTER TABLE DEMO_USERS
ADD USER_EMAIL VARCHAR2(30)

ALTER TABLE DEMO_CUSTOMERS
DROP COLUMN CUST_EMAIL

ALTER TABLE DEMO_CUSTOMERS
ADD USER_ID NUMBER(22) CONSTRAINT user_id_fk references DEMO_USERS(USER_ID);

ALTER TABLE DEMO_PRODUCT_INFO
ADD productImageURL VARCHAR2(400)


-- Update Table
update DEMO_USERS
set USER_EMAIL = 'infy@gmail.com',
password = '123456'
where USER_ID = 1


